// CamiTube — app logic
// Reads the pre-built videos.json (generated by GitHub Actions using yt-dlp,
// no API key involved) and renders it. Everything below is just
// display, filtering, pagination, and the video player.

let channels = [];        // [{ channelId, handle, title }]
let pool = [];             // all videos, sorted newest first
let activeFilter = "all";  // "all" (last LATEST_WINDOW_DAYS days) or a channelId (full history)
let shown = 0;              // how many of the current filtered list are rendered
let nameByChannelId = {};  // channelId -> short display name

const $ = (sel) => document.querySelector(sel);
const grid = $("#grid");
const statusEl = $("#status");
const loadMoreBtn = $("#loadMoreBtn");
const filterRow = $("#filterRow");
const updatedAtEl = $("#updatedAt");

// ---------- Watched videos (stored locally in this browser only) ----------

const WATCHED_LS_KEY = "camitube_watched";
let watchedIds = new Set(JSON.parse(localStorage.getItem(WATCHED_LS_KEY) || "[]"));

function isWatched(videoId) {
  return watchedIds.has(videoId);
}

function markWatched(videoId) {
  if (watchedIds.has(videoId)) return;
  watchedIds.add(videoId);
  localStorage.setItem(WATCHED_LS_KEY, JSON.stringify([...watchedIds]));
}

function setStatus(text, isError) {
  if (!text) { statusEl.hidden = true; return; }
  statusEl.hidden = false;
  statusEl.textContent = text;
  statusEl.classList.toggle("error", !!isError);
}

function formatDate(iso) {
  const d = new Date(iso);
  return d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
}

function formatRelative(iso) {
  const seconds = Math.floor((Date.now() - new Date(iso).getTime()) / 1000);
  if (seconds < 60) return "just now";
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `${days}d ago`;
  const weeks = Math.floor(days / 7);
  if (weeks < 5) return `${weeks}w ago`;
  const months = Math.floor(days / 30);
  if (months < 12) return `${months}mo ago`;
  const years = Math.floor(days / 365);
  return `${years}y ago`;
}

function currentList() {
  if (activeFilter === "all") {
    const cutoff = Date.now() - LATEST_WINDOW_DAYS * 24 * 60 * 60 * 1000;
    return pool.filter((v) => new Date(v.publishedAt).getTime() >= cutoff);
  }
  return pool.filter((v) => v.channelId === activeFilter);
}

function renderFilters() {
  filterRow.innerHTML = "";
  const latestPill = document.createElement("button");
  latestPill.className = "pill" + (activeFilter === "all" ? " active" : "");
  latestPill.textContent = "Latest videos";
  latestPill.addEventListener("click", () => setFilter("all"));
  filterRow.appendChild(latestPill);

  channels.forEach((c) => {
    const pill = document.createElement("button");
    pill.className = "pill" + (activeFilter === c.channelId ? " active" : "");
    pill.textContent = nameByChannelId[c.channelId] || c.title;
    pill.addEventListener("click", () => setFilter(c.channelId));
    filterRow.appendChild(pill);
  });
}

function setFilter(channelId) {
  activeFilter = channelId;
  shown = 0;
  renderFilters();
  renderGrid(true);
}

function renderGrid(reset) {
  const list = currentList();
  if (reset) grid.innerHTML = "";

  if (list.length === 0) {
    setStatus(
      activeFilter === "all"
        ? "No videos from the last week — pick a channel above to see its full history."
        : "No videos yet — check back after the next scheduled update."
    );
    loadMoreBtn.hidden = true;
    return;
  }
  setStatus("");

  const nextShown = Math.min(shown + PAGE_SIZE, list.length);
  list.slice(shown, nextShown).forEach((video) => grid.appendChild(renderCard(video)));
  shown = nextShown;

  loadMoreBtn.hidden = shown >= list.length;
}

function renderCard(video) {
  const card = document.createElement("button");
  card.className = "card" + (isWatched(video.videoId) ? " watched" : "");
  card.type = "button";
  card.dataset.videoId = video.videoId;

  const thumbWrap = document.createElement("div");
  thumbWrap.className = "thumb-wrap";
  const img = document.createElement("img");
  img.src = video.thumb;
  img.alt = "";
  img.loading = "lazy";
  thumbWrap.appendChild(img);

  if (video.membersOnly) {
    const badge = document.createElement("span");
    badge.className = "badge-members";
    badge.textContent = "Members only";
    thumbWrap.appendChild(badge);
  }

  const watchedBadge = document.createElement("span");
  watchedBadge.className = "badge-watched";
  watchedBadge.textContent = "✓ Watched";
  thumbWrap.appendChild(watchedBadge);

  const title = document.createElement("div");
  title.className = "card-title";
  title.textContent = video.title;

  const meta = document.createElement("div");
  meta.className = "card-meta";
  const channelName = document.createElement("span");
  channelName.textContent = nameByChannelId[video.channelId] || video.channelTitle;
  const date = document.createElement("span");
  date.className = "card-date";
  date.textContent = formatRelative(video.publishedAt);

  meta.appendChild(channelName);
  meta.appendChild(date);

  card.appendChild(thumbWrap);
  card.appendChild(title);
  card.appendChild(meta);

  card.addEventListener("click", () => openPlayer(video));
  return card;
}

// ---------- Player ----------

const playerOverlay = $("#playerOverlay");
const playerFrame = $("#playerFrame");
const playerTitle = $("#playerTitle");
const playerSub = $("#playerSub");

function openPlayer(video) {
  markWatched(video.videoId);
  const cardEl = grid.querySelector(`[data-video-id="${video.videoId}"]`);
  if (cardEl) cardEl.classList.add("watched");

  const iframe = document.createElement("iframe");
  iframe.src = `https://www.youtube.com/embed/${video.videoId}?autoplay=1`;
  iframe.title = video.title;
  iframe.allow = "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture";
  iframe.allowFullscreen = true;
  playerFrame.innerHTML = "";
  playerFrame.appendChild(iframe);
  playerTitle.textContent = video.title;
  playerSub.textContent = `${video.channelTitle} · ${formatDate(video.publishedAt)}`;
  playerOverlay.hidden = false;
}

function closePlayer() {
  playerOverlay.hidden = true;
  playerFrame.innerHTML = "";
}

$("#closePlayerBtn").addEventListener("click", closePlayer);
playerOverlay.addEventListener("click", (e) => {
  if (e.target === playerOverlay) closePlayer();
});
document.addEventListener("keydown", (e) => {
  if (e.key === "Escape" && !playerOverlay.hidden) closePlayer();
});

// ---------- Load more ----------

loadMoreBtn.addEventListener("click", () => renderGrid(false));

// ---------- Boot ----------

async function boot() {
  setStatus("Loading videos…");
  try {
    const res = await fetch("./videos.json", { cache: "no-store" });
    if (!res.ok) throw new Error(`videos.json request failed (${res.status})`);
    const data = await res.json();

    channels = data.channels || [];
    nameByChannelId = {};
    channels.forEach((c) => {
      nameByChannelId[c.channelId] = DISPLAY_NAMES[c.handle] || c.title;
    });

    pool = (data.videos || []).slice().sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt));

    if (data.generatedAt) {
      updatedAtEl.textContent = `Updated ${formatDate(data.generatedAt)}`;
    }

    renderFilters();
    shown = 0;
    renderGrid(true);
  } catch (err) {
    setStatus(`Couldn't load the video list: ${err.message}`, true);
  }
}

boot();
